### ISSUE TITLE
[Help] Sidemenu toggle not working

### ISSUE THREAD

**Issue by HardikDG** [erdkse/adminlte-3-angular#13]
Hello,

Your demo is working great.
I am trying to implement it the same way you have implemented it. 
I am having issue in the toggle of the menu. On click of a button, the menu is shown/hide but the main view and header's width is not increased if the menu is closed. 

Do you know what can be the issue in it? 

Also I have one more question. How you have added JS imports. I didn't find it anywhere. I may be missing any import

**Comment by HardikDG** [comment]
The issue is I didn't add classes in the Index.html. It is fixed now

**Comment by erdkse** [comment]
@HardikDG I checked drawer works as expected. Angular blocks animation I need to add Angular animations to provide it.

I didnt use any external jquery libraries. Project is written by pure Angular and It is not finished yet but anyone can use it It is enough
