### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by peppeantonini** [erdkse/adminlte-3-angular#24]
Taking a test for the mobile environment, the result is this
![standard](https://user-images.githubusercontent.com/8817237/110129012-b6934200-7dc7-11eb-91e9-cb19369fcff8.JPG)
![angular](https://user-images.githubusercontent.com/8817237/110129023-b98e3280-7dc7-11eb-8e0d-0bf5741c0fd0.JPG)

**Comment by erdkse** [comment]
Fixed!
