### ISSUE TITLE
Login api was triggering 2 times in the console

### ISSUE THREAD

**Issue by k-jayaraman** [erdkse/adminlte-3-angular#27]
Hello @erdkse 

Is there any specific reason the following end point was calling 2 times while sigin. Kindly need your advice on this issue.

<img width="1789" alt="Screenshot 2021-05-29 at 9 15 54 PM" src="https://user-images.githubusercontent.com/55172929/120076471-4a249800-c0c3-11eb-9c8a-a1380dc8ee66.png">

**Comment by erdkse** [comment]
Thanks for informing! Will take a look in my free time.

**Comment by k-jayaraman** [comment]
Hi @erdkse  , Can we work on this issue

**Comment by erdkse** [comment]
You mean together? I am afraid I can't schedule a meeting for it due to lack of free time. I prefer to do it alone. But you can send a PR as well.

**Comment by k-jayaraman** [comment]
> You mean together? I am afraid I can't schedule a meeting for it due to lack of free time. I prefer to do it alone. But you can send a PR as well.

Okay @erdkse  , Kindly take your time . By the way will report one more issue to make the UI perfect one .

Thanks for doing great work.

**Comment by erdkse** [comment]
Thank you too for being my QA master :)

**Comment by erdkse** [comment]
Looks like this is solved!!
