### ISSUE TITLE
Unable to retrieve the user data after the hard page refresh.

### ISSUE THREAD

**Issue by k-jayaraman** [erdkse/adminlte-3-angular#28]
Hello @erdkse ,

I've modified the UI little to support external apis but am unable to retrieve the user data after the hard page refresh.

```
 getUserProfile() {
        return this.http.get<any>(`${environment.apiUrl}/get_user_profile`,{ headers: this.headers })
        .subscribe((res: any) => {
            this.user = res;
        })
    }
```

I can't get the this ```this.user``` values after the hard page refresh

**Comment by erdkse** [comment]
Hard to tell the reason. But customization of the project is out of my scope.
