### ISSUE TITLE
There is no multilevel menu supported in the UI

### ISSUE THREAD

**Issue by k-jayaraman** [erdkse/adminlte-3-angular#29]
Hello @erdkse  , 

We would like to have the multilevel menu in the upcoming dashboard.

<img width="244" alt="Screenshot 2021-06-19 at 6 15 45 PM" src="https://user-images.githubusercontent.com/55172929/122642911-72377200-d12a-11eb-8a4d-fe7c1f63b54c.png">

**Comment by k-jayaraman** [comment]
Hello @erdkse  , Kindly  fix the above mentioned issue

**Comment by mchdhid** [comment]
hy @erdkse up for this

**Comment by k-jayaraman** [comment]
Hello @erdkse , Kindly fix the above mentioned issue

**Comment by erdkse** [comment]
Hey guys! Sorry, I am so busy with my job. This need to wait for some time.

**Comment by erdkse** [comment]
Working on it #31 !!
