### ISSUE TITLE
Which auth server this template uses at gatekeeper-api.profabric.tech?

### ISSUE THREAD

**Issue by luisrigoni** [erdkse/adminlte-3-angular#32]
Hi, 

I would like to host my own auth server. Looking at `gatekeeper-cliet-sdk/axios.js` there is:

```
const intance = axios.create({
    baseURL: `https://gatekeeper-api.profabric.tech`
});
```

This may be a silly question, but I can't figure out what is running there.
Which server/tech/stack are you running?
Can you show some direction on how we can create/host a custom auth server?

**Comment by erdkse** [comment]
This is my custom implemented server. I am planning to open it for public usage. I will inform you from here when it is ready.

**Comment by VirginEnt** [comment]
Hey, 
is there any news on that? I would be interested as well!

BTW: Great job :-)

BR, 
Daniel

**Comment by erdkse** [comment]
this package usage is dropped. I am closing the issue.
