### ISSUE TITLE
Gatekeeper Error

### ISSUE THREAD

**Issue by eddohjean** [erdkse/adminlte-3-angular#34]
Hi, 

I have this error when run ng serve 

error: src/main.ts:12:12 - error TS2339: Property 'initialize' does not exist on type 'IGatekeeper'.

12 Gatekeeper.initialize('9966bf1b-5da5-4b55-9301-86f9f0c77aaf');

**Comment by erdkse** [comment]
Hey, which version of Gatekeeper you are using?

**Comment by erdkse** [comment]
the package usage is dropped, closing the issue.
