### ISSUE TITLE
Missing menu animations (please take a look at this implementation)

### ISSUE THREAD

**Issue by ajjp** [erdkse/adminlte-3-angular#35]
Hi, thanks for the good work and for sharing it! 👍

I added the menu animation to menu-item component (with code from another project). I also replaced the IMHO awkward left chevron with right chevron, so if you want to keep the original AdminLTE please modify accordingly.

I placed the changes in the attached file.

P.S. Do you have plans to add sub menus to sub menus like the original AdminLTE has?

[adminlte-3-angular-ajjp-changes.zip](https://github.com/erdkse/adminlte-3-angular/files/8839883/adminlte-3-angular-ajjp-changes.zip)

**Comment by erdkse** [comment]
Hey, thank you for your work. Could you please create a PR for that? I have added submenus, I don't know which version you are using.

PS. I have no intention of sticking with the original AdminLTE

**Comment by ajjp** [comment]
Hey, thank you. I created the PR.

I forgot to mention earlier that I also added dynamic icon classes to the menu.

About submenus, I was referring to have more than one level of submenu. I tried to add one but I got error.

**Comment by erdkse** [comment]
Thank you @ajjp ! Looks perfect! I have merged it!

**Comment by dalevaldez09** [comment]
Hi @erdkse , How to implement multi-level menus?
