### ISSUE TITLE
AdminLte sidebar search

### ISSUE THREAD

**Issue by dalevaldez09** [erdkse/adminlte-3-angular#38]
How to implement adminlte sidebar search? expecially this` $('[data-widget="sidebar-search"]').SidebarSearch('toggle')`

**Comment by erdkse** [comment]
I will implement this in next week with the other issues. @dalevaldez09

**Comment by dalevaldez09** [comment]
> I will implement this in next week with the other issues. @dalevaldez09

Thanks

**Comment by dalevaldez09** [comment]
> I will implement this in next week with the other issues. @dalevaldez09

@erdkse , Is this implemented already?

**Comment by dalevaldez09** [comment]
@erdkse is this already implemented?

**Comment by erdkse** [comment]
@dalevaldez09 , It is implemented within this PR #43
