### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by mohdwaseem** [erdkse/adminlte-3-angular#42]
Is this theme support rtl?

**Comment by erdkse** [comment]
I really don't know, if you check out the real AdminLTE project and tell me I can implement @mohdwaseem

**Comment by mohdwaseem** [comment]
@erdkse I checked AdminLTE V3 not supports rtl, future release of AdminLTE V4  supports rtl

**Comment by erdkse** [comment]
Great! I will add an implementation for V4 too, I can include in it @mohdwaseem
