### ISSUE TITLE
update to Angular 16

### ISSUE THREAD

**Issue by olayaherrera** [erdkse/adminlte-3-angular#51]
Hi,

I try to update the project to angular 16 but i got always this error con web console 

Error: NG0209: Unexpected type of the `APP_INITIALIZER` token value (expected an array, but got object). Please check that the `APP_INITIALIZER` token is configured as a `multi: true` provider. Find more at https://angular.io/errors/NG0209

**Comment by erdkse** [comment]
Hi @olayaherrera , thank you for reporting. This issue is related to a dependency package. I am aware of it and waiting for this package maintainer to fix this issue. I will update to version 16 after it.

**Comment by olayaherrera** [comment]
nothing yet ?

**Comment by erdkse** [comment]
yeah, I checked, they updated. I will upgrade to v16 at this weekend @olayaherrera

**Comment by albertopinilla** [comment]
Please, I also have the same problem

**Comment by jhasumit100** [comment]
Hi @erdkse ,
is there any update on updated version?

**Comment by GwtLabs** [comment]
Removing the **ProfabricComponentsModule** from package **@profabric/angular-components** fixed this problem.

**Comment by olayaherrera** [comment]
> Removing the **ProfabricComponentsModule** from package **@profabric/angular-components** fixed this problem.

but Profabric is necessary for the theme to function, where exactly did you remove it from?


i got errors

Error: src/app/components/sidebar-search/sidebar-search.component.html:1:1 - error NG8001: 'pf-dropdown' is not a known element:
1. If 'pf-dropdown' is an Angular component, then verify that it is part of this module.
2. If 'pf-dropdown' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by erdkse** [comment]
Angular version is updated to v17.1.0, thank you for the patience folks
