### ISSUE TITLE
Sign in error: Failed to fetch

### ISSUE THREAD

**Issue by glewe** [erdkse/adminlte-3-angular#52]
Local login does not work on my end.
In Chrome, error message is: Faild to fetch
In FF, error message is: Network error when attempting to fetch resource

Any idea?

best regards,
g

**Comment by g7figueiredo** [comment]
the same error occurred to me, were you able to resolve it?

**Comment by glewe** [comment]
No, unfortunately not. I abandoned this library therefore.

**Comment by erdkse** [comment]
this issue is resolved. I dropped the usage of a library that causes this issue. Thank you for the patience folks,
