### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by g7figueiredo** [erdkse/adminlte-3-angular#53]
This error is occurring when trying to log in

![error](https://github.com/erdkse/adminlte-3-angular/assets/4819978/1551ac42-b849-44c7-942e-9fd650f52428)

**Comment by Ntonsite** [comment]
Author of this project, did not mention about how authentication details are being retrieved, is it API set up with DB or else.

Am also stacked at this point.

**Comment by erdkse** [comment]
This issue is resolved. I dropped usage of a dependency that causes this error. Sorry for the delay folks.

**Comment by Ntonsite** [comment]
This is working great now. Thank you for the support. @erdkse
